name: Packer
on:
    push:
        branches:
            - master

jobs:
    PackerImage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Packer
              uses: hashicorp/setup-packer@v3.1.0
              with:
                packer-version: '1.11.2'

            - name: Initialize Packer Image
              run: |
                packer init .

            - name: Building Packer Image
              run: |
                packer build .

              env:
                PKR_VAR_client_id: ${{ secrets.CLIENT_ID }}
                PKR_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
                PKR_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
                PKR_VAR_tenant_id: ${{ secrets.TENANT_ID }}